FROM golang:1.25-alpine

RUN apk add --no-cache ca-certificates tzdata curl bash git

WORKDIR /app

ENV GOTOOLCHAIN=auto

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD ["sh", "-c", "go test -buildvcs=false ./unit_tests/... -v -count=1 && go test -buildvcs=false ./API_tests/... -v -count=1"]
